import static org.gradle.api.JavaVersion.VERSION_1_8

buildscript {
  dependencies {
    classpath libs.publishPlugin
  }

  repositories {
    mavenCentral()
  }
}

apply plugin: 'java-library'
apply plugin: 'com.vanniktech.maven.publish'

java {
  sourceCompatibility = VERSION_1_8
  targetCompatibility = VERSION_1_8
}

dependencies {
  api libs.moshi

  testImplementation libs.junit
  testImplementation libs.truth
}

repositories {
  mavenCentral()
}
